#infinispan.client.hotrod.context-initializers=org.rlnieto.pruebas.BookSchemaImpl
#infinispan.client.hotrod.server_list=cluster-datagrid-test.apps.sharedocp4upi411ovn.lab.upshift.rdu2.redhat.com
infinispan.client.hotrod.server_list=localhost
#infinispan.client.hotrod.server_list=infinispan-server-datagrid.apps-crc.testing:32208
#infinispan.client.hotrod.server_list=192.168.0.22

#infinispan.client.hotrod.auth_username=admin
#infinispan.client.hotrod.auth_password=admin
infinispan.client.hotrod.auth_username=operator
infinispan.client.hotrod.auth_password=IZoOoTNfoBgchpDm

infinispan.client.hotrod.java_serial_allowlist=org.rlnieto.pruebas.model.*
infinispan.remote.java-serial-allowlist=org.rlnieto.pruebas.model.*

# Workaround para levantarlo con docker compose, parece que durante el
# descubrimiento llega una ip que no es local
# El fallo no ocurre si usamos directamente docker:
#    podman run -it --rm -p 11222:11222 -e USER="admin" -e PASS="admin" --net=host quay.io/infinispan/server:13.0
infinispan.client.hotrod.client_intelligence=BASIC